//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public string id { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public string code { get; set; }
        public string error { get; set; }
        public string url { get; set; }
        public string source { get; set; }
        public string logtype { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public string loglevel { get; set; }
        public string insertdate { get; set; }
        public string insertuser { get; set; }
    }
}
