//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appreciatiion
    {
        public string id { get; set; }
        public string award { get; set; }
        public string employeeid { get; set; }
        public string date { get; set; }
        public string summary { get; set; }
        public string photo { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
