//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public string id { get; set; }
        public string companyid { get; set; }
        public string packageid { get; set; }
        public string paymentdate { get; set; }
        public string nextpaymentdate { get; set; }
        public string transactionid { get; set; }
        public string amount { get; set; }
        public string paymentgateway { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Package Package { get; set; }
    }
}
