//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string country { get; set; }
        public string mobile { get; set; }
        public string gender { get; set; }
        public string Language { get; set; }
        public string clientcategory { get; set; }
        public string clientsubcategory { get; set; }
        public string Companyname { get; set; }
        public string companywebsite { get; set; }
        public string taxname { get; set; }
        public string gstvatnumber { get; set; }
        public string companyphone { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postalcode { get; set; }
        public string companyaddress { get; set; }
        public string shippingaddress { get; set; }
        public string addedby { get; set; }
        public string note { get; set; }
        public string insertdate { get; set; }
        public string employeeid { get; set; }
        public string companyid { get; set; }
    
        public virtual company001 company001 { get; set; }
    }
}
