//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.billings = new HashSet<billing>();
        }
    
        public string id { get; set; }
        public string packageid { get; set; }
        public string companyname { get; set; }
        public string companyemail { get; set; }
        public string companyphone { get; set; }
        public string companywebsite { get; set; }
        public string timezone { get; set; }
        public string language { get; set; }
        public string currency { get; set; }
        public string address { get; set; }
        public string acctname { get; set; }
        public string acctemail { get; set; }
        public string packageid1 { get; set; }
        public string details { get; set; }
        public string insertdate { get; set; }
        public string status { get; set; }
        public string photo { get; set; }
        public string url { get; set; }
        public string expdate { get; set; }
        public string employees { get; set; }
        public string clients { get; set; }
        public string invoices { get; set; }
        public string storage { get; set; }
        public string estimates { get; set; }
        public string projects { get; set; }
        public string tasks { get; set; }
        public string leads { get; set; }
        public string orders { get; set; }
        public string tickets { get; set; }
        public string contacts { get; set; }
        public string amount { get; set; }
        public string paymentdate { get; set; }
        public string nextpaymentdate { get; set; }
        public string licenceexpireson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billing> billings { get; set; }
        public virtual Package Package { get; set; }
    }
}
