//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        internal string companyid1;
        internal string leadid1;

        public string id { get; set; }
        public string leadcontactid { get; set; }
        public string name { get; set; }
        public string pipeline { get; set; }
        public string dealstages { get; set; }
        public string dealvalue { get; set; }
        public string closedate { get; set; }
        public string dealcategory { get; set; }
        public string dealagent { get; set; }
        public string product { get; set; }
        public string dealwatcher { get; set; }
        public string insertdate { get; set; }
    
        public virtual Lead_Contact Lead_Contact { get; set; }
    }
}
