//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Appreciatiions = new HashSet<Appreciatiion>();
            this.Deals = new HashSet<Deal>();
            this.Lead_Contact = new HashSet<Lead_Contact>();
            this.Lead_Contact1 = new HashSet<Lead_Contact>();
            this.Leaves = new HashSet<Leave>();
            this.Shift_Roster = new HashSet<Shift_Roster>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string dob { get; set; }
        public string designation { get; set; }
        public string department { get; set; }
        public string email { get; set; }
        public string country { get; set; }
        public string mobile { get; set; }
        public string gender { get; set; }
        public string joiningdate { get; set; }
        public string reportingto { get; set; }
        public string Language { get; set; }
        public string status { get; set; }
        public string userrole { get; set; }
        public string insertdate { get; set; }
        public string about { get; set; }
        public string hourlyrate { get; set; }
        public string slackmemberid { get; set; }
        public string skills { get; set; }
        public string probationenddate { get; set; }
        public string noticeperiodstartdate { get; set; }
        public string noticeperiodenddate { get; set; }
        public string employmenttype { get; set; }
        public string maritalstatus { get; set; }
        public string businessaddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appreciatiion> Appreciatiions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead_Contact> Lead_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead_Contact> Lead_Contact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift_Roster> Shift_Roster { get; set; }
    }
}
