//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public string id { get; set; }
        public string name { get; set; }
        public string leavetype { get; set; }
        public string status { get; set; }
        public string Duration { get; set; }
        public string date { get; set; }
        public string leavefile { get; set; }
        public string createdby { get; set; }
        public string reasonforabsence { get; set; }
        public string insertdate { get; set; }
        public string employeeid { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
