//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offlinerequest
    {
        public string id { get; set; }
        public string company { get; set; }
        public string package { get; set; }
        public string paymentby { get; set; }
        public string created { get; set; }
        public string status { get; set; }
        public string insertdate { get; set; }
    }
}
