//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.billings = new HashSet<billing>();
            this.Companies = new HashSet<Company>();
        }
    
        public string id { get; set; }
        public string packagename { get; set; }
        public string monthlyprice { get; set; }
        public string annualprice { get; set; }
        public string currency { get; set; }
        public string filestoragemb { get; set; }
        public string maxemployees { get; set; }
        public bool moduleinpackage1 { get; set; }
        public bool moduleinpackage2 { get; set; }
        public bool moduleinpackage3 { get; set; }
        public bool moduleinpackage4 { get; set; }
        public bool moduleinpackage5 { get; set; }
        public bool moduleinpackage6 { get; set; }
        public bool moduleinpackage7 { get; set; }
        public bool moduleinpackage8 { get; set; }
        public bool moduleinpackage9 { get; set; }
        public bool moduleinpackage10 { get; set; }
        public bool moduleinpackage11 { get; set; }
        public bool moduleinpackage12 { get; set; }
        public bool moduleinpackage13 { get; set; }
        public bool moduleinpackage14 { get; set; }
        public bool moduleinpackage15 { get; set; }
        public bool moduleinpackage16 { get; set; }
        public bool moduleinpackage17 { get; set; }
        public bool moduleinpackage18 { get; set; }
        public bool moduleinpackage19 { get; set; }
        public bool moduleinpackage20 { get; set; }
        public bool moduleinpackage21 { get; set; }
        public bool moduleinpackage22 { get; set; }
        public bool moduleinpackage23 { get; set; }
        public bool moduleinpackage24 { get; set; }
        public bool moduleinpackage25 { get; set; }
        public bool moduleinpackage26 { get; set; }
        public bool moduleinpackage27 { get; set; }
        public bool moduleinpackage28 { get; set; }
        public bool moduleinpackage29 { get; set; }
        public bool moduleinpackage30 { get; set; }
        public bool moduleinpackage31 { get; set; }
        public bool moduleinpackage32 { get; set; }
        public bool moduleinpackage33 { get; set; }
        public bool moduleinpackage34 { get; set; }
        public string status { get; set; }
        public string insertdate { get; set; }
        public string packagetype { get; set; }
        public string description { get; set; }
        public string packagecategory { get; set; }
        public string paymentdate { get; set; }
        public string nextpaymentdate { get; set; }
        public string licenceexpireson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billing> billings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
    }
}
