//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personneldocument
    {
        public string id { get; set; }
        public string doc_order { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public string notes { get; set; }
        public string status { get; set; }
        public string url { get; set; }
        public string doctype { get; set; }
        public string documentid { get; set; }
        public string cat_id { get; set; }
    
        public virtual document document { get; set; }
        public virtual personel_files_cat personel_files_cat { get; set; }
    }
}
