//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift_Roster
    {
        public string id { get; set; }
        public string Departmentid { get; set; }
        public string employeeshift { get; set; }
        public string shiftfrom { get; set; }
        public string shiftto { get; set; }
        public string remarks { get; set; }
        public string shiftfile { get; set; }
        public string createdby { get; set; }
        public string insertdate { get; set; }
        public string employeeid { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
