//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StickyNote
    {
        public string id { get; set; }
        public string title { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string createdby { get; set; }
        public string updateby { get; set; }
        public string description { get; set; }
        public string color { get; set; }
    }
}
